//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kocsis
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public int Id { get; set; }
        public string AutoNeve { get; set; }
        public string Üzemanyag { get; set; }
        public Nullable<decimal> Fogyasztas { get; set; }
        public Nullable<byte> Kor { get; set; }
    }
}
